name: test-build-release
on: push
jobs:
  tests:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Markdown lint
        uses: actionshub/markdownlint@v1.1.0

      - name: Setup Java
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '11.0.4' # The JDK version to make available on the path. Takes a whole or semver JDK version, or 1.x syntax (e.g. 1.8 => Jdk 8.x). To specify a specific version for JDK 8 or older use the following pattern (8.0.x)

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-sonarqube
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-sonarqube
            ${{ runner.os }}-maven-

      - name: Maven clean
        run: mvn clean

      - name: Sonar
        run: >
          mvn --batch-mode package verify sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.projectKey=p1nkun1c0rns_sonarcloud-test
          -Dsonar.organization=p1nkun1c0rns
          -Dorg.slf4j.simpleLogger.defaultLogLevel=warn
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar_login }}
